<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MoraleTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('morales')->insert([
            [
                'morale' => 'You don’t have to see the whole staircase, just take the first step. – Martin Luther King, Jr.'
            ],
            [
                'morale' => 'An important key to success is self-confidence. An important key to self-confidence is preparation. – Arthur Ashe'
            ],
            [
                'morale' => 'It isn’t your position, but your disposition, that makes you happy or unhappy. – Bruce Bichel et al.'
            ],
            [
                'morale' => 'Be the change you want to see in the world. – Mahatma Gandhi'
            ],
            [
                'morale' => 'Don’t go where the path may lead. Go instead where there is no path and leave a trail. – Ralph Waldo Emerson'
            ],
            [
                'morale' => 'If you think you’re too small to be effective, you have never been in bed with a mosquito. – Betty Reese'
            ],
            [
                'morale' => 'You can do something no one else can do in a fashion no one else can do it. – Max Lucado'
            ],
            [
                'morale' => 'What a woman / man accomplishes depends on what she / he believes. – Bankers Bulletin'
            ],
            [
                'morale' => 'Always do right; this will gratify some people and astonish the rest. – Mark Twain'
            ],
            [
                'morale' => 'I like dreams of the future better than the history of the past. – Thomas Jefferson'
            ],
            [
                'morale' => 'If you see someone without a smile, give them one of yours. – Richard De Haan'
            ],
            [
                'morale' => 'What is important is ideas. If you have ideas, you have the main asset you need, and there isn’t any limit what you can do with your business and your life. – Harvey Firestone'
            ],
            [
                'morale' => 'Put your heart, mind, intellect and soul even to your smallest acts. This is the secret of success. – Swami Sivananda'
            ],
            [
                'morale' => 'What lies before us and what lies behind us are small matters, compare to what lies within us. – Ralph Waldo Emerson'
            ],
            [
                'morale' => 'Everyone can be great . . . because anybody can serve. You only need a soul generated by love. – Martin Luther King, Jr.'
            ],
            [
                'morale' => 'Obstacles are those frightful things you see when you take your eyes off the goal. – Hannah More'
            ],
            [
                'morale' => 'Don’t let what you cannot do interfere with what you can do. – John Wooden'
            ],
            [
                'morale' => 'To be successful, you can’t just run on the fast track; run on your track. – John C. Maxwell'
            ],
            [
                'morale' => 'Everything is possible for him who believes. – The Bible'
            ],
            [
                'morale' => 'Challenges make you discover things about yourself that you never really knew. - Cicely Tyson'
            ],
            [
                'morale' => 'Attempt the impossible in order to improve your work. – Bette Davis'
            ],
            [
                'morale' => 'The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt.'
            ],
            [
                'morale' => 'When you affirm big, believe big and pray big, big things happen. – Norman Vincent Peale'
            ],
            [
                'morale' => 'Everyone has the power to impact the outcome of his life. The way to do it is to focus on today. . . It is too late for yesterday. And you can’t depend on tomorrow. - John C. Maxwell'
            ],
            [
                'morale' => 'Doing the best at this moment puts you in the best place for the next moment. – Oprah Winfrey'
            ],
            [
                'morale' => 'In the confrontation between the stream and the rock, the stream always wins—not through strength, by through perseverance. – H, Jackson Brown'
            ],
            [
                'morale' => 'Consider the postage stamp. It secures success through its ability to stick to one thing till it gets there. – Josh Billings'
            ],
            [
                'morale' => 'Diligence is not easy, but we can’t reach our goals without it. – Henry Cloud et al.'
            ],
            [
                'morale' => 'What counts is not necessarily the size of the dog in the fight; it’s the size of the fight in the dog. – Dwight Eisenhower'
            ],
            [
                'morale' => 'Those who hope in the Lord will renew their strength. They will soar on wings like eagles. – The Bible'
            ],
            [
                'morale' => 'Integrity is formed, not born, one decision at a time. – Jeff O’Leary'
            ],
            [
                'morale' => 'In the middle of difficulty lies opportunity. – Albert Einstein'
            ],
            [
                'morale' => 'Honor is self-esteem made visible in action. – Ayn Rand'
            ],
            [
                'morale' => 'Every single successful person I’ve ever spoken to had a turning point. The turning point was when they made a clear, specific unequivocal decision that they were not going to live like this anymore; they were going to achieve success. – Brian Tracy'
            ],
            [
                'morale' => 'Show class, have pride and display character. If you do, winning takes care of itself. – Paul “Bear” Bryant.'
            ],
            [
                'morale' => 'The most rewarding things you can do in life are often the ones that look like they cannot be done. – Arnold Palmer'
            ],
            [
                'morale' => 'Don\'t judge each day by the harvest you reap, but by the seeds you plant. - Robert Louis Stevenson'
            ],
            [
                'morale' => 'There’s always a way through things if you work hard enough and look close. It all depends on your level of determination. – Liz Murray'
            ],
            [
                'morale' => 'Well done is better than well said. – Benjamin Franklin'
            ],
            [
                'morale' => 'People forget how fast you did a job—but they remember how well you did it. – Howard Newton'
            ],
            [
                'morale' => 'I will go anywhere provided it’s forward. – David Livingstone'
            ],
            [
                'morale' => 'Nothing liberates our greatness like the desire to help, the desire to serve. – Marianne Williamson'
            ],
            [
                'morale' => 'I resolve never to do anything I wouldn’t do if it were the last hour of my life. – Jonathan Edwards'
            ],
            [
                'morale' => 'In everything, do to others what you would have them do to you. – The Bible'
            ],
            [
                'morale' => 'We can do no great things; only small things with great love. – Mother Teresa'
            ],
            [
                'morale' => 'Life is 10% what happens to you and 90% how you respond to it. – Chuck Swindoll'
            ],
            [
                'morale' => 'Don’t be afraid to take a big step. You can’t cross a chasm in two small jumps. – David Lloyd George'
            ],
            [
                'morale' => 'You have not lived a perfect day, even though you have earned your money, unless you have done something for someone, who will never be able to repay you. – Ruth Smeltzer'
            ],
            [
                'morale' => 'Nice guys may appear to finish last, but usually they are running in a different race. – Blanchard and Peale'
            ],
            [
                'morale' => 'Up is not an easy direction. It defies gravity, both cultural and magnetic. – Mike Abrashoff'
            ],
            [
                'morale' => 'Let gratitude for the past inspire us with trust for the future. – Francois Fenelon'
            ],
        ]);
    }
}
